<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>db44105a-8d60-4c4d-8497-9ba481d84c50</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.10" />
    <PackageReference Include="Seq.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.CommandLine.Hosting" Version="0.4.0-alpha.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ase.Ef.Core\Ase.Ef.Core.csproj" />
    <ProjectReference Include="..\Ase.Infrastructure\Ase.Infrastructure.csproj" />
    <ProjectReference Include="..\Ase.Shopify.Graphql\Ase.Shopify.Graphql.csproj" />
    <ProjectReference Include="..\Ase.Shopify\Ase.Shopify.csproj" />
    <ProjectReference Include="..\BeadTrim\Ase.BeadTrim.Abstractions\Ase.BeadTrim.Abstractions.csproj" />
    <ProjectReference Include="..\BeadTrim\Ase.BeadTrim\Ase.BeadTrim.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Options\" />
  </ItemGroup>

</Project>
